"""add snapshot_hash integrity

Revision ID: bb64cf8bef22
Revises: ef495c93e5eb
Create Date: 2026-09-29 21:43:59.883010
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bb64cf8bef22'
down_revision: Union[str, None] = 'ef495c93e5eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_records', sa.Column('snapshot_hash', sa.String(length=64), nullable=True, comment='快照 HMAC-SHA256 指纹；读取判分基线前必须验签（防改库改分）'))
    # ### end Alembic commands ###
    # 存量回填：为已有快照按"当前内容"补指纹。
    # 只能保证此后（迁移生效后）的篡改可检出——历史上已被改过的快照会拿到"被改后内容"的合法指纹，
    # 这是任何后验签名的固有边界（诚实记录进 D4）。
    import json as _json

    from app.snapshot_guard import sign_snapshot

    conn = op.get_bind()
    rows = conn.execute(
        sa.text("SELECT id, snapshot_json FROM exam_records WHERE snapshot_hash IS NULL")
    ).fetchall()
    for rid, raw in rows:
        obj = _json.loads(raw) if isinstance(raw, str) else raw
        conn.execute(
            sa.text("UPDATE exam_records SET snapshot_hash = :h WHERE id = :i"),
            {"h": sign_snapshot(obj), "i": rid},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_records', 'snapshot_hash')
    # ### end Alembic commands ###
