"""init 7 tables

Revision ID: ef495c93e5eb
Revises: 
Create Date: 2026-09-20 21:03:44.511626
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'ef495c93e5eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_categories_name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False, comment='teacher|student'),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_users_username'),
    comment='用户；username 统一小写存储'
    )
    op.create_table('papers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('end_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False, comment='draft|published|closed'),
    sa.Column('total_score', sa.Numeric(precision=6, scale=1), nullable=False, comment='对外一律叫 full_score'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='试卷'
    )
    op.create_index('ix_papers_creator_status', 'papers', ['creator_id', 'status'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False, comment='single|multiple|judge|short'),
    sa.Column('content', sa.String(length=5000), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=True, comment='2~6 项，如 ["A. x","B. y"]'),
    sa.Column('correct_answer', sa.String(length=255), nullable=False, comment='规范见 D2 §6.1；short 允许空串'),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='题库'
    )
    op.create_index('ix_questions_category_type', 'questions', ['category_id', 'type'], unique=False)
    op.create_table('exam_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('deadline_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False, comment='=min(started+duration,end_at)；仅 T1 写入，永不更新'),
    sa.Column('submitted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False, comment='in_progress|final'),
    sa.Column('submit_kind', sa.String(length=10), nullable=True, comment='normal|timeout；NULL=未交'),
    sa.Column('review_state', sa.String(length=10), nullable=True, comment='pending|final；NULL=未交'),
    sa.Column('auto_score', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('earned_score', sa.Numeric(precision=6, scale=1), nullable=True, comment='已得总分'),
    sa.Column('cheat_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False, comment='判分基线（含正确答案，绝不出现在任何响应里）'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'student_id', name='uq_exam_paper_student'),
    comment='考试记录（核心表，两维状态机）'
    )
    op.create_index('ix_exam_status_deadline', 'exam_records', ['status', 'deadline_at'], unique=False)
    op.create_index('ix_exam_student_started', 'exam_records', ['student_id', 'started_at'], unique=False)
    op.create_table('paper_questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'question_id', name='uq_pq_paper_question'),
    comment='试卷-题目关联，逐题分值'
    )
    op.create_table('answers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('student_answer', sa.String(length=1000), nullable=False, comment="未答=''"),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=1), nullable=True, comment='NULL=待批'),
    sa.Column('review_status', sa.String(length=15), nullable=True, comment='仅 short：needs_review|reviewed|skipped'),
    sa.Column('review_comment', sa.String(length=255), nullable=True),
    sa.Column('answered_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['exam_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'question_id', name='uq_answers_record_question'),
    comment='作答明细（upsert 语义，支撑续考与判分补齐）'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """按外键安全顺序整表删除。

    不要照抄 autogenerate 生成的 drop_index：MySQL 拒绝删除"正在支撑某个外键"的索引，
    会报 1553 (Cannot drop index ...: needed in a foreign key constraint)。
    drop_table 会连带删掉它上面的索引，所以整表删除即可（实测修正，见 D4）。
    """
    op.drop_table('answers')
    op.drop_table('paper_questions')
    op.drop_table('exam_records')
    op.drop_table('questions')
    op.drop_table('papers')
    op.drop_table('users')
    op.drop_table('categories')
